### ISSUE TITLE
Local dev installation fails due to explicit version number in setup.cfg

### ISSUE THREAD

**Issue by bschroeter** [CABLE-LSM/benchcab#129]
Installing via `pip install -e .` fails due to an explicit version number in the setup.cfg, as per https://github.com/invl/retry/issues/8

This can be addressed by commenting out the version number in setup.cfg, but looks to be associated with extracting the semantic version number from the repo.

Possible symptom of misconfigured automatic extraction of git version number.

**Comment by bschroeter** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/129?planning-poker) with Zenhub @ccarouge @SeanBryan51

**Comment by SeanBryan51** [comment]
We might have to rework the changes I made when implementing the `--version` command line flag in #55. In that PR, the SSOT of the version number is defined in setup.cfg so that I could get the version number in the source code, and get the version number in meta.yaml.

It seems if I comment out the version number from setup.cfg and then run `conda build -c conda-forge .` in the project root, the benchcab version in the local channel is `None`:
```
$ conda search --use-local benchcab
Loading channels: done
# Name                       Version           Build  Channel
benchcab                        None           py_92  scratch/tm70/sb8430/conda/bld
```

**Comment by SeanBryan51** [comment]
It would be great if we could get the version number that is inferred by pbr into meta.yaml somehow. I'll look into it.

**Comment by ccarouge** [comment]
@SeanBryan51 Should we rather look at this from the viewpoint of #152 ? So a complete redesign of the setup using `.toml` instead of just fixing this particular aspect of it? I would assume a good solution for #152 would fix this issue as well.

**Comment by SeanBryan51** [comment]
@ccarouge yep I agree. This issue can probably wait until we get around to #152 as it only effects us (developers).

**Comment by ccarouge** [comment]
Discussed at meeting: will investigate `versioneer`

**Comment by SeanBryan51** [comment]
@bschroeter suggested using [grayskull](https://github.com/conda/grayskull) for automatically publishing pypi packages to conda

**Comment by SeanBryan51** [comment]
Versioneer ([vendored mode](https://github.com/python-versioneer/python-versioneer?tab=readme-ov-file#vendored-mode)) looks promising, the version string inferred by versioneer can be found by `conda` (see [here](https://github.com/CABLE-LSM/benchcab/commit/7c064817b42537784ea5f50e0440e8e55a542c29) for the implementation):
```
$ pip install --user -q . && pip list | grep benchcab
benchcab           3.0.0+12.g7c06481
$ conda render . | grep version
  version: 3.0.0+12.g7c06481
```
To move to versioneer, we will need to deprecate support for [PBR](https://docs.openstack.org/pbr/latest/index.html) so that we can use the versioneer version string instead of the PBR version string. In the above changes, this meant using [the vanilla setuptools setup.cfg options](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html) instead of [the additional options provided by PBR](https://docs.openstack.org/pbr/latest/user/using.html#setup-cfg).
