### ISSUE TITLE
Change source of namelist files

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/benchcab#13]
CABLE v3 currently needs 3 namelist files to run:

- cable.nml
- pft_params.nml
- cable_soilparm.nml

cable.nml is currently sourced from CABLE-AUX and the other 2 from the source code (offline/). Now the example work directory has a namelists/ sub-directory to store examples of those. We need to modify benchcab to source the namelists from this sub-directory.

**Comment by har917** [comment]
This fix appears to have broken benchcab.  A fresh run on 14-6-2022 raises an error at line 50 of benchtree.py.  

This appears to be copying the structure/files in nml_dir into the site_dir but failing because there is no nml_dir to copy from at this time.  Possibly a sequencing issue.
![Screenshot 2022-06-14 111511](https://user-images.githubusercontent.com/94580228/173490010-82857900-92aa-4979-acb6-fa21513f4fce.jpg)
