### ISSUE TITLE
Investigate the use of pbr?

### ISSUE THREAD

**Issue by bschroeter** [CABLE-LSM/benchcab#152]
https://docs.openstack.org/pbr/latest/index.html

This might help resolve #129 and others.

**Comment by SeanBryan51** [comment]
I think we should remove the [ChangeLog](https://github.com/CABLE-LSM/benchcab/blob/b5fe7fd12c2670c15a4d4b8269cfdccce521fede/ChangeLog) and [AUTHORS](https://github.com/CABLE-LSM/benchcab/blob/b5fe7fd12c2670c15a4d4b8269cfdccce521fede/AUTHORS) files from the repository, or at least have these files be updated via some CI action. In my opinion these files are a bit redundant since this information is contained in git anyway.

**Comment by SeanBryan51** [comment]
Perhaps its time we move to using a `pyproject.toml` file to configure the setuptools build (see [Configuring setuptools using pyproject.toml files](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)). Some reasons why we might want to this are:
- Compliance with [PEP 518](https://peps.python.org/pep-0518/)
- `pyproject.toml` support for [Ruff](https://docs.astral.sh/ruff/)

We can use [`setuptools_scm`](https://setuptools-scm.readthedocs.io/en/latest/) to extract the package version from git.

**Comment by SeanBryan51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CABLE-Dev-643e35a4354310001fc40202/issues/CABLE-LSM/benchcab/152?planning-poker) with Zenhub @bschroeter @ccarouge

**Comment by SeanBryan51** [comment]
Closing this issue as PBR was deprecated in #228.
